cricapp/urls.py
from django.urls import path

from . import views


app_name = 'cricapp'

urlpatterns = [
    path(  # home
        '',
        views.home,
        name='home'
    ),
    path(  # Add team
        'team/add',
        views.add_team,
        name='add_team'
    ),
    path(  # List of teams
        'team/list',
        views.teams,
        name='teams'
    ),
    path(  # Team detail
        'team/<int:pk>/',
        views.team_detail,
        name='team_detail'
    ),
    path(  # Add player
        'player/add',
        views.add_player,
        name='add_player'
    ),
    path(  # Add player
        'player/add/<int:pk>/',
        views.add_player,
        name='add_team_player'
    ),
    path(  # List of players
        'player/list',
        views.players,
        name='players'
    ),
    path(   # Player details
        'player/<int:id>/',
        views.player_details,
        name='player_details'
    ),
    path(  # Matches
        'matches',
        views.matches,
        name='matches'
    ),
    path(
        'matches/fixtures',
        views.create_matches_fixtures,
        name='create_fixtures'
    ),
    path(
        'match/<int:pk>',
        views.match_details,
        name='match_details'
    ),
    path(
        'all_fixtures',
        views.fixture_list,
        name='all_fixture_list'
    ),
    path(
        'all_fixtures/<str:trnmt_id>/',
        views.fixture_list,
        name='single_fixture_list'
    ),
    path(
        'process/<int:team_id>/<int:match_id>/<str:trnmt_id>/',
        views.select_match_winner,
        name='select_match_winner'
    ),
    path(
        'semi_process/<int:team1_id>/<int:team2_id>/<str:trnmt_id>/',
        views.select_semifinalist,
        name='select_semifinalist'
    ),
    path(
        'final_process/<int:team1_id>/<int:team2_id>/<str:trnmt_id>/',
        views.select_finalist,
        name='select_finalist'
    )
]

cricket_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cricapp.urls'), name='cricapp')
]

cricapp/models.py
from django.db import models


class Team(models.Model):

    name = models.CharField(max_length=255)
    logo_uri = models.CharField(max_length=2048)
    club_state = models.CharField(max_length=255)
    points = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    modified_at = models.DateTimeField(auto_now=True, editable=False)

    class Meta:
        verbose_name_plural = "Teams"

    def __str__(self):
        return self.name


class Player(models.Model):

    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    image_uri = models.CharField(max_length=2048)
    jersey_number = models.PositiveIntegerField()
    country = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    modified_at = models.DateTimeField(auto_now=True, editable=False)

    class Meta:
        verbose_name_plural = "Players"

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Match(models.Model):

    team1 = models.ForeignKey(
        Team, on_delete=models.CASCADE, related_name='team1')
    team2 = models.ForeignKey(
        Team, on_delete=models.CASCADE, related_name='team2')
    match_number = models.CharField(max_length=128)
    level = models.CharField(max_length=100, blank=True, null=True)
    tournament_id = models.CharField(max_length=255)
    team_winner = models.ForeignKey(
        Team, on_delete=models.CASCADE, related_name='team_winner', blank=True, null=True)
    location = models.CharField(max_length=128)
    stadium = models.CharField(max_length=128)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    modified_at = models.DateTimeField(auto_now=True, editable=False)

    class Meta:
        verbose_name_plural = "Matches"

cricapp/views.py
import itertools
import random
from django.db.utils import IntegrityError
from django.shortcuts import get_object_or_404, render, redirect
from .model_forms import TeamForm, PlayerForm
from .models import *
from django.contrib import messages


def home(request):
    """
    Display Point and match details on the home page.

    Parameters
    ----------
    request : HTTP request object

    Returns : Render the home page template.

    """
    matches = Match.objects.all().order_by('-match_number')
    teams = Team.objects.all()
    context = {
        'matches': matches,
        'teams': teams
    }
    return render(request, 'home.html', context)


def add_team(request):
    """
    Provide functionality to add team.

    Parameters
    ----------
    request : HTTP request object

    Returns : Render the add team page template.

    """
    if request.method == 'POST':
        form = TeamForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Team has been added successfully')
        return redirect('cricapp:teams')
    else:
        form = TeamForm()
    context = {
        'form': form
    }
    return render(request, 'teams/add.html', context)


def team_detail(request, pk=None):
    """
    List all the details of a particular Team.

    Parameters
    ----------
    request : HTTP request object
    pk: Primary key of the Team entity

    Returns : Render the add team page template.

    """
    if pk is not None:
        context = dict()
        context['team'] = Team.objects.get(pk=pk)
        context['players'] = Player.objects.filter(team=pk)
        return render(request, 'teams/details.html', context)
    else:
        return redirect('home')


def teams(request):
    """
    List all of the teams.

    Parameters
    ----------
    request : HTTP request object

    """

    context = {
        'teams_list': Team.objects.all(),
    }
    return render(request, 'teams/list.html', context)


def add_player(request, pk=None):
    """
    Provide functionality to add player.

    Parameters
    ----------
    request : HTTP request object

    Returns : Render the add player template.

    """
    if request.method == 'POST':
        form = PlayerForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Player has been added successfully')
        return redirect('cricapp:players')
    else:
        team = pk if id is not None else ''
        form = PlayerForm(initial={'team': team})

    context = {'form': form}
    return render(request, 'players/add.html', context)


def players(request):
    """
    List players.

    Parameters
    ----------
    request : HTTP request object.
    Returns : Render the list player template.

    """

    players = Player.objects.all()
    context = {'players_list': players}
    return render(request, 'players/list.html', context)


def player_details(request, id):
    """
    List details of a particular player.

    Parameters
    ----------
    request : HTTP request object.
    Returns : Render the add player detail template.

    """

    player = get_object_or_404(Player, pk=id)
    team = Team.objects.filter(
        pk=player.team_id)[0].name
    context = {
        'player': player,
        'team': team
    }

    return render(request, 'players/detail.html', context)


def matches(request):
    """
    List Matches.

    Parameters
    ----------
    request : HTTP request object
    Returns : Render the match listing template.

    """
    context = {'match_list': Match.objects.all()}
    return render(request, 'matches/list.html', context)


def create_matches_fixtures(request):
    """
    Dynamically create match fixrures.

    Parameters
    ----------
    request : HTTP request object.

    Returns : Render the create tournament template.

    """
    Match.objects.all().delete()
    Team.objects.all().update(**{'points': 0})
    all_teams = Team.objects.all()

    match_possibilities = itertools.combinations(all_teams, 2)

    all_matches = list()
    tournament_no = str(random.randint(1, 999999999999999))
    i = 1
    for combination in match_possibilities:
        all_matches.append(combination)
        Match(**{'team1': combination[0], 'team2': combination[1], 'level': 'Round1', 'tournament_id': tournament_no, 'location': f'location_{i}', 'stadium': f'stadium_{i}',
                 'match_number': f'match_{i}'}).save()
        i = i+1

    return render(request, 'matches/create_tournament.html',
                  {'tournament_no': tournament_no, 'match_possibilities': all_matches})


def match_details(request, pk):
    """
    Display match details.

    Parameters
    ----------
    request : HTTP request object
    pk: primary key of entity Match.

    -------------------
    Returns : Render the match detail template.

    """
    match = get_object_or_404(Match, pk=pk)
    context = {'match': match}
    return render(request, 'matches/detail.html', context)


def fixture_list(request, trnmt_id=None):
    """
    Match fixtures.

    Parameters
    ----------
    request : HTTP request object.
    trnmt_id: Tournament id.

    -------------------
    Returns : Render the match fixture template.


    """
    context = dict()
    if trnmt_id is None:
        trnmt_id = Match.objects.all()[0].tournament_id

    # tournament id
    context['trmt_id'] = trnmt_id
    # teams
    context['teams'] = Team.objects.values(
        'name', 'points').all().order_by('-points')
    # Get fixture list
    all_fixtures = Match.objects.filter(tournament_id=trnmt_id)

    if Match.objects.filter(tournament_id=trnmt_id, team_winner__isnull=False).count() == all_fixtures.count():
        # Qualified teams
        context['qualified_teams'] = [{'name': team.name, 'id': team.id, 'is_win': Match.objects.filter(team_winner=team, level='Semi').count()}
                                      for team in Team.objects.all().order_by('-points')[0:4]]

    # Teams who will participate in final and winner.
    if Match.objects.filter(level='Semi', tournament_id=trnmt_id, team_winner__isnull=False).count() == 2:
        context['final_teams'] = [{'name': match.team_winner.name, 'id': match.team_winner.id}
                                  for match in Match.objects.filter(level='Semi', tournament_id=trnmt_id)]
        context['final_winner'] = Match.objects.filter(level='Final')[
            0].team_winner.name if Match.objects.filter(level='Final').count() > 0 else False
    # matches
    matches = list()
    for fix in all_fixtures:
        is_done = 'Yes' if fix.team_winner is not None else 'No'
        matches.append({'team1': fix.team1, 'team2': fix.team2, 'location': fix.location, 'stadium': fix.stadium, 'trmt_id': fix.tournament_id,
                        'team1_id': fix.team1.id, 'team2_id': fix.team2.id, 'match_id': fix.id, 'match_win': fix.team_winner, 'is_completed': is_done})

    context['matches'] = matches

    return render(request, 'matches/fixtures.html', context)


def select_match_winner(request, team_id=None, match_id=None, trnmt_id=None):
    """
    Functionality to select match winner.

    Parameters
    ----------
    request : HTTP request object
    team_id: Winner Team id.
    match_id: Match id.
    trnmt_id: Tournament id.

    ----------------------------
    return: redirects to fixture listing page.


    """
    if team_id is not None and match_id is not None and trnmt_id is not None:
        point = Team.objects.get(pk=team_id).points
        Match.objects.filter(pk=match_id).update(**{'team_winner': team_id})
        Team.objects.filter(pk=team_id).update(**{'points': int(point)+2})
        return redirect('cricapp:single_fixture_list', trnmt_id)
    else:
        return redirect('cricapp:all_fixture_list')


def select_semifinalist(request, team1_id=None, team2_id=None, trnmt_id=None):
    """
    Functionality to select semi finalist.

    Parameters
    ----------
    request : HTTP request object
    team1_id: Team one id.
    team2_id: Team two id.
    trnmt_id: Tournament id.

    ----------------------------
    return: redirects to fixture listing page.

    """
    if team1_id is not None and team2_id is not None and trnmt_id is not None:
        match_number = Match.objects.filter(tournament_id=trnmt_id).count() + 1
        Match(**{'team1_id': team1_id, 'team2_id': team2_id, 'level': 'Semi', 'tournament_id': trnmt_id,
                 'match_number': match_number, 'team_winner_id': team1_id}).save()
        return redirect('cricapp:single_fixture_list', trnmt_id)
    else:
        return redirect('cricapp:all_fixture_list')


def select_finalist(request, team1_id=None, team2_id=None, trnmt_id=None):
    """
    Functionality to select finalist.

    Parameters
    ----------
    request : HTTP request object
    team1_id: Team one id.
    team2_id: Team two id.
    trnmt_id: Tournament id.

    ----------------------------
    return: redirects to fixture listing page.

    """
    if team1_id is not None and team2_id is not None and trnmt_id is not None:
        match_number = Match.objects.filter(tournament_id=trnmt_id).count() + 1
        Match(**{'team1_id': team1_id, 'team2_id': team2_id, 'level': 'Final', 'tournament_id': trnmt_id,
                 'match_number': match_number, 'team_winner_id': team1_id}).save()
        return redirect('cricapp:single_fixture_list', trnmt_id)
    else:
        return redirect('cricapp:all_fixture_list')

cricapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />

    {% if title %}
    <title>{{ title }} | Cricket</title>
    {% else %}
    <title>Cricket</title>
    {% endif %}
  </head>
  <body>
	<header>
    	{% include 'header.html' %}
	</header>

	<main>
		<div class="container mt-5">
      <div class="row">
        <!--Main content-->
        <div class="col-md-12">{% block content %}{% endblock content%}</div>
        <!--Main content ends-->
        
      </div>
    </div>
	</main>
    
	<footer>
		{% include 'footer.html' %}
	</footer>

  </body>
</html>

cricapp/templates/footer.html
<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
      integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
      crossorigin="anonymous"
    ></script>

cricapp/templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'cricapp:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cricapp:create_fixtures'%}">Create Tournament</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cricapp:teams'%}">Teams</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cricapp:players'%}">Players</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cricapp:all_fixture_list' %}">Create Fixture</a>
      </li>
    </ul>
  </div>
</nav>

cricapp/templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1>The Cricpro App</h1>
<a href="{% url 'cricapp:create_fixtures' %}" class="btn btn-primary">Set up new Tournament</a>

<h2>Point table</h2>
<table class="table">
    <tr>
        <th>Team</th>
        <th>Points</th>
    </tr>
    {% for team in teams %}
    <tr>
        <td>{{team.name}}</td>
        <td>{{team.points}}</td>
    </tr>
    {% endfor %}
</table>

<h2>Match Details</h2>
<table class="table">
    <tr>
        <th>Match #</th>
        <th>Location</th>
        <th>Stadium</th>
        <th>Teams</th>
        <th>Won</th>
        <th>Details</th>
    </tr>
    {% for match in matches %}
    <tr>
        <td>
            {% if match.level == 'Semi' %}
            <strong>Semi Finals</strong>
            {% elif match.level == 'Final' %}
            <strong>Finals</strong>
            {% else %}
            {{ match.match_number }}
            {% endif %}</td>
        <td>{{ match.location }}</td>
        <td>{{ match.stadium }}</td>
        <td><strong>{{match.team1}}</strong> <em>v/s</em> <strong>{{match.team2}}</strong></td>
        <td>{{match.team_winner}}</td>
        <td><a href="{% url 'cricapp:match_details' match.id %}">Get details</a></td>
    </tr>
    {% empty %}
    <tr>
        <td colspan="4">No match exist.</td>
    </tr>
    {% endfor %}
</table>
<ul>

</ul>
{% endblock content%}